### PR TITLE
Non ghcid test loop. 

### PR DESCRIPTION
**Pull request by benkolera**
This works pretty well but will spam out the tests pretty badly if you save a lot of files while the tests run. Still nicer than ghcid and having to restart it.

### CODE REVIEW

**Comment by nghamilton** [comment]
Maybe make it .ghc.* so it doesn't delete .ghci files?

**Comment by benkolera** [comment]
See db0f2d21fc78e923546c791f1fbe23aee3ca02cd for that fix @nghamilton

**Comment by ajmcmiddlin** [comment]
What does "spam out the tests" mean? It will start a new run of the tests every time there's a file change, regardless of whether one is running?

**Comment by benkolera** [comment]
Yes.

**Pull request merged**
